services:
  frontend:
    build:
      context: ./frontend
    image: mikeczak/smartui-frontend:latest
    container_name: smart_ui_frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  nginx:
    image: mikeczak/smartui-nginx:latest
    build:
      context: .
      dockerfile: ./local/Dockerfile
    container_name: smart_ui_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ssl_data:/etc/nginx/ssl/:ro

  backend:
    build:
      context: ./backend
    image: mikeczak/smartui-backend:latest
    container_name: smart_ui_backend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - form_data:/app/src/data/:rw
      - ./.env:/app/src/backend/.env:ro

volumes:
  ssl_data:
    external:
      name: ssl_data
  form_data:
    external:
      name: form_data